# Generated by Django 4.2.2 on 2023-07-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_work_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workgroup', to='group.workgroup'),
        ),
    ]
