# Generated by Django 4.2.3 on 2023-07-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_work_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_group',
        ),
    ]
