# Generated by Django 4.2.3 on 2023-07-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_work_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'),
                                                        ('female', 'Female'),
                                                        ('other', 'Other')],
                                   max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_marketplace',
            field=models.BooleanField(default=False),
        ),
    ]
