# Generated by Django 4.2.3 on 2023-07-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('accounts', '0006_user_birth_date_user_gender_user_is_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='marketplace.marketplace'),
        ),
    ]
