version: "3"

services:
  db:
    image: mysql:8
    container_name: galaxytech
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: galaxytech
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    network_mode: bridge
  redis:
    image: "redis:latest"
    container_name: "redis-galaxytech"
    ports:
      - "6379:6379"